In [29]:
import numpy as np

In [30]:
A = np.array([[1, 2], [7,8]])
B = np.array([[3, 5], [1,6]])

### Hitunglah:

- 2*A
- 2+A
- A+B
- A-B
- determinan A
- invers dari B, simpan jadi matriks D
- transpose D
- nilai eigen dan vektor eigen dari A dan B

In [31]:
#Ketik Kode disini

print(2*A)
print(2+A)
print(A+B)
print(A-B)
print(np.linalg.det(A))

[[ 2  4]
 [14 16]]
[[ 3  4]
 [ 9 10]]
[[ 4  7]
 [ 8 14]]
[[-2 -3]
 [ 6  2]]
-6.0


In [32]:
print(np.linalg.inv(B))

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


In [33]:
D = np.linalg.inv(B)

In [34]:
print(D)

[[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]


In [35]:
D_T = D.T

In [36]:
D, D_T

(array([[ 0.46153846, -0.38461538],
        [-0.07692308,  0.23076923]]),
 array([[ 0.46153846, -0.07692308],
        [-0.38461538,  0.23076923]]))

In [37]:
print(np.linalg.eig(A))

(array([-0.62347538,  9.62347538]), array([[-0.77640358, -0.22592838],
       [ 0.63023605, -0.97414391]]))


In [38]:
print(np.linalg.eig(A)[0])

[-0.62347538  9.62347538]


In [39]:
print(np.linalg.eig(A)[1])

[[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]


In [40]:
print(np.linalg.eig(B))

(array([1.8074176, 7.1925824]), array([[-0.97271381, -0.76626443],
       [ 0.23200828, -0.64252535]]))


In [41]:
print(np.linalg.eig(B)[0])

[1.8074176 7.1925824]


In [42]:
print(np.linalg.eig(B)[1])

[[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [43]:
#Tunjukkan bedanya di kodingan di bawah ini

print(B*D)

[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]


In [46]:
B, D

(array([[3, 5],
        [1, 6]]),
 array([[ 0.46153846, -0.38461538],
        [-0.07692308,  0.23076923]]))

In [48]:
print(np.matmul(B, D))

[[ 1.00000000e+00  0.00000000e+00]
 [-5.55111512e-17  1.00000000e+00]]


### output jawaban:

perkalian entry = [[ 1.38461538, -1.92307692], [-0.07692308, 1.38461538]]

perkalian matriks = [[ 1.00000000e+00, -1.11022302e-16], [ 1.11022302e-16, 1.00000000e+00]]

In [28]:
np.__version__

'1.20.3'

In [24]:
pip install --upgrade numpy

ERROR: Could not install packages due to an OSError: [WinError 5] Access is denied: 'C:\\Users\\USER\\anaconda3\\Lib\\site-packages\\~umpy\\core\\_multiarray_tests.cp39-win_amd64.pyd'
Consider using the `--user` option or check the permissions.




  Attempting uninstall: numpy
    Found existing installation: numpy 1.20.3
    Uninstalling numpy-1.20.3:
      Successfully uninstalled numpy-1.20.3
